import type { SanityProduct, JournalDoc } from "./sanity/types";

export const MOCK_PRODUCTS: SanityProduct[] = [
  {
    _id: "mock-w1",
    name: "Velvet Petals",
    slug: "velvet-petals",
    audience: "Women",
    family: "Floral",
    mood: ["Romantic", "Elegant", "Date Night"],
    price: "From KSh 3,500",
    shortDescription: "Warm floral · vanilla · soft musk. A scent that settles like a second skin.",
    notes: ["White peony", "Jasmine", "Vanilla", "Soft musk", "Sandalwood"],
    mainImage: null,
    featured: true,
    _mockImageUrl: "/images/products/women-1.webp",
  },
  {
    _id: "mock-w2",
    name: "Rose Smoke",
    slug: "rose-smoke",
    audience: "Women",
    family: "Oud",
    mood: ["Mysterious", "Bold", "Evening", "Signature Scent"],
    price: "From KSh 4,200",
    shortDescription: "Rose · incense · amber woods. Romantic, dark, and completely unforgettable.",
    notes: ["Bulgarian rose", "Oud", "Incense", "Amber", "Patchouli"],
    mainImage: null,
    featured: true,
    _mockImageUrl: "/images/products/women-2.webp",
  },
  {
    _id: "mock-w3",
    name: "Clean Silk",
    slug: "clean-silk",
    audience: "Women",
    family: "Musk",
    mood: ["Clean", "Soft", "Daily Wear", "Office"],
    price: "From KSh 3,800",
    shortDescription: "White musk · pear · airy powder. Light enough to forget you're wearing it—until someone asks.",
    notes: ["Pear", "White musk", "Iris", "Cashmeran", "Light powder"],
    mainImage: null,
    featured: true,
    _mockImageUrl: "/images/products/women-3.webp",
  },
  {
    _id: "mock-m1",
    name: "Midnight Cedar",
    slug: "midnight-cedar",
    audience: "Men",
    family: "Woody",
    mood: ["Bold", "Mysterious", "Evening", "Signature Scent"],
    price: "From KSh 4,000",
    shortDescription: "Cedar · spice · smoky amber. The kind of scent that walks into a room first.",
    notes: ["Cedarwood", "Cardamom", "Black pepper", "Smoky amber", "Vetiver"],
    mainImage: null,
    featured: true,
    _mockImageUrl: "/images/products/men-1.webp",
  },
  {
    _id: "mock-m2",
    name: "Quiet Leather",
    slug: "quiet-leather",
    audience: "Men",
    family: "Leather",
    mood: ["Elegant", "Warm", "Luxury", "Office"],
    price: "From KSh 4,500",
    shortDescription: "Leather · tonka · dry woods. Minimal. Precise. Worn by people who don't need to explain themselves.",
    notes: ["Leather accord", "Tonka bean", "Birch", "Dry woods", "Grey amber"],
    mainImage: null,
    featured: true,
    _mockImageUrl: "/images/products/men-2.webp",
  },
  {
    _id: "mock-m3",
    name: "Ocean Noir",
    slug: "ocean-noir",
    audience: "Men",
    family: "Aquatic",
    mood: ["Fresh", "Clean", "Daily Wear", "All Season"],
    price: "From KSh 3,600",
    shortDescription: "Mineral fresh · iris · musk. Like standing at the edge of the Indian Ocean at night.",
    notes: ["Sea accord", "Iris", "Violet leaf", "White musk", "Ambergris"],
    mainImage: null,
    featured: true,
    _mockImageUrl: "/images/products/men-3.jpg",
  },
];

export const MOCK_JOURNAL: JournalDoc[] = [
  {
    _id: "journal-1",
    slug: "how-to-layer-fragrances",
    title: "How to Layer Fragrances Without Getting It Wrong",
    excerpt: "Layering is an art, not a science. Here's a simple guide to building a signature scent combination that works for your skin and your lifestyle.",
    content: [
      "Layering fragrances is one of the most personal things you can do with scent. The goal isn't complexity—it's depth.",
      "Start with your base. Apply your heavier, woodier scent first—directly to clean skin. This becomes the foundation everything else sits on.",
      "Add your statement. Your floral or spicy layer goes on next, on the same pulse points. Don't rub. Let it settle.",
      "Finish light. A clean musk or light citrus on top ties it together and gives you a fresh opening without hiding the warmth underneath.",
      "The best combinations we've found: Cedar + Rose Smoke, Clean Silk + Velvet Petals, Ocean Noir + Midnight Cedar.",
    ],
    publishedAt: "2025-03-01T09:00:00",
  },
  {
    _id: "journal-2",
    slug: "nairobi-scent-guide",
    title: "A Scent Guide for Nairobi's Seasons",
    excerpt: "Nairobi's climate is its own thing—cool mornings, warm afternoons, and long dry spells. Here's how to dress your scent accordingly.",
    content: [
      "Most fragrance advice is written for European climates. We wrote this for Nairobi.",
      "March–May (Long Rains): Humid mornings call for lighter applications. Musks and clean florals perform beautifully—they won't turn sharp in the heat. Try Clean Silk or Ocean Noir.",
      "June–August (Cool Season): This is the best time to wear your heaviest, most complex scents. The cool dry air lets them open slowly. Midnight Cedar and Rose Smoke come into their own here.",
      "October–November (Short Rains): Warm and unpredictable. Versatile scents that work in both heat and cool—Velvet Petals and Quiet Leather are reliable choices.",
    ],
    publishedAt: "2025-03-15T09:00:00",
  },
  {
    _id: "journal-3",
    slug: "making-fragrance-last",
    title: "Why Your Fragrance Fades — and How to Fix It",
    excerpt: "If your scent disappears within an hour, the problem usually isn't the fragrance. It's how you're applying it.",
    content: [
      "Fragrance longevity is almost entirely about skin preparation and application technique.",
      "Moisturise first. Dry skin absorbs fragrance quickly and holds it poorly. Apply an unscented lotion to your pulse points before you spray—it gives the fragrance something to cling to.",
      "Don't rub. Rubbing your wrists together breaks the top notes and makes the scent fade faster. Spray and leave it.",
      "Pulse points matter. Wrists, neck, behind the ears, inner elbows. Anywhere your blood runs close to the surface—the warmth diffuses the scent naturally throughout the day.",
    ],
    publishedAt: "2025-04-01T09:00:00",
  },
];
