import type { WPPost } from "./wp";

export const MOCK_SCENTS: WPPost[] = [
  {
    id: 1,
    slug: "velvet-petals",
    title: { rendered: "Velvet Petals" },
    excerpt: { rendered: "<p>Warm floral · vanilla · soft musk. A scent that settles like a second skin.</p>" },
    content: { rendered: "<p>Velvet Petals opens with a breath of white florals before settling into warm vanilla and the softest musk you'll ever wear. Long-lasting, feminine without being loud.</p><p><strong>Notes:</strong> White peony, jasmine, vanilla, soft musk, sandalwood.</p>" },
    date: "2025-01-10T09:00:00",
    acf: { price: "From KSh 3,500" },
    _embedded: { "wp:featuredmedia": [{ source_url: "/images/products/women-1.webp", alt_text: "Velvet Petals" }] },
  },
  {
    id: 2,
    slug: "rose-smoke",
    title: { rendered: "Rose Smoke" },
    excerpt: { rendered: "<p>Rose · incense · amber woods. Romantic, dark, and completely unforgettable.</p>" },
    content: { rendered: "<p>Rose Smoke pairs the romance of deep rose with smoky incense and warm amber woods. It's bold, deliberate, and stays close to the skin for hours.</p><p><strong>Notes:</strong> Bulgarian rose, oud, incense, amber, patchouli.</p>" },
    date: "2025-01-15T09:00:00",
    acf: { price: "From KSh 4,200" },
    _embedded: { "wp:featuredmedia": [{ source_url: "/images/products/women-2.webp", alt_text: "Rose Smoke" }] },
  },
  {
    id: 3,
    slug: "clean-silk",
    title: { rendered: "Clean Silk" },
    excerpt: { rendered: "<p>White musk · pear · airy powder. Light enough to forget you're wearing it—until someone asks.</p>" },
    content: { rendered: "<p>Clean Silk is the scent of fresh laundry and quiet luxury. Airy, powdery, and effortlessly elegant from morning to evening.</p><p><strong>Notes:</strong> Pear, white musk, iris, cashmeran, light powder.</p>" },
    date: "2025-01-20T09:00:00",
    acf: { price: "From KSh 3,800" },
    _embedded: { "wp:featuredmedia": [{ source_url: "/images/products/women-3.webp", alt_text: "Clean Silk" }] },
  },
  {
    id: 4,
    slug: "midnight-cedar",
    title: { rendered: "Midnight Cedar" },
    excerpt: { rendered: "<p>Cedar · spice · smoky amber. The kind of scent that walks into a room first.</p>" },
    content: { rendered: "<p>Midnight Cedar is confident and grounded. Dry cedar anchored by cardamom spice and deep smoky amber—it commands attention without demanding it.</p><p><strong>Notes:</strong> Cedarwood, cardamom, black pepper, smoky amber, vetiver.</p>" },
    date: "2025-02-01T09:00:00",
    acf: { price: "From KSh 4,000" },
    _embedded: { "wp:featuredmedia": [{ source_url: "/images/products/men-1.webp", alt_text: "Midnight Cedar" }] },
  },
  {
    id: 5,
    slug: "quiet-leather",
    title: { rendered: "Quiet Leather" },
    excerpt: { rendered: "<p>Leather · tonka · dry woods. Minimal. Precise. Worn by people who don't need to explain themselves.</p>" },
    content: { rendered: "<p>Quiet Leather is restrained luxury in a bottle. Soft leather accord warmed by tonka bean and dry woods—understated and magnetic.</p><p><strong>Notes:</strong> Leather accord, tonka bean, birch, dry woods, grey amber.</p>" },
    date: "2025-02-05T09:00:00",
    acf: { price: "From KSh 4,500" },
    _embedded: { "wp:featuredmedia": [{ source_url: "/images/products/men-2.webp", alt_text: "Quiet Leather" }] },
  },
  {
    id: 6,
    slug: "ocean-noir",
    title: { rendered: "Ocean Noir" },
    excerpt: { rendered: "<p>Mineral fresh · iris · musk. Clean depth. Like standing at the edge of the Indian Ocean at night.</p>" },
    content: { rendered: "<p>Ocean Noir captures that specific feeling of cool sea air mixed with something deeper beneath—mineral freshness, powdery iris, and a long musky trail.</p><p><strong>Notes:</strong> Sea accord, iris, violet leaf, white musk, ambergris.</p>" },
    date: "2025-02-10T09:00:00",
    acf: { price: "From KSh 3,600" },
    _embedded: { "wp:featuredmedia": [{ source_url: "/images/products/men-3.jpg", alt_text: "Ocean Noir" }] },
  },
];

export const MOCK_JOURNAL: WPPost[] = [
  {
    id: 10,
    slug: "how-to-layer-fragrances",
    title: { rendered: "How to Layer Fragrances Without Getting It Wrong" },
    excerpt: { rendered: "<p>Layering is an art, not a science. Here's a simple guide to building a signature scent combination that works for your skin and your lifestyle.</p>" },
    content: { rendered: "<p>Layering fragrances is one of the most personal things you can do with scent. The goal isn't complexity—it's depth.</p><h2>Start with your base</h2><p>Apply your heavier, woodier scent first—directly to clean skin. This becomes the foundation everything else sits on.</p><h2>Add your statement</h2><p>Your floral or spicy layer goes on next, on the same pulse points. Don't rub. Let it settle.</p><h2>Finish light</h2><p>A clean musk or light citrus on top ties it together and gives you a fresh opening without hiding the warmth underneath.</p><p>The best combinations we've found: Cedar + Rose Smoke, Clean Silk + Velvet Petals, Ocean Noir + Midnight Cedar.</p>" },
    date: "2025-03-01T09:00:00",
  },
  {
    id: 11,
    slug: "nairobi-scent-guide",
    title: { rendered: "A Scent Guide for Nairobi's Seasons" },
    excerpt: { rendered: "<p>Nairobi's climate is its own thing—cool mornings, warm afternoons, and long dry spells. Here's how to dress your scent accordingly.</p>" },
    content: { rendered: "<p>Most fragrance advice is written for European climates. We wrote this for Nairobi.</p><h2>March–May (Long Rains)</h2><p>Humid mornings call for lighter applications. Musks and clean florals perform beautifully—they won't turn sharp in the heat. Try Clean Silk or Ocean Noir.</p><h2>June–August (Cool Season)</h2><p>This is the best time to wear your heaviest, most complex scents. The cool dry air lets them open slowly. Midnight Cedar and Rose Smoke come into their own here.</p><h2>October–November (Short Rains)</h2><p>Warm and unpredictable. Versatile scents that work in both heat and cool—Velvet Petals and Quiet Leather are reliable choices.</p>" },
    date: "2025-03-15T09:00:00",
  },
  {
    id: 12,
    slug: "making-fragrance-last",
    title: { rendered: "Why Your Fragrance Fades — and How to Fix It" },
    excerpt: { rendered: "<p>If your scent disappears within an hour, the problem usually isn't the fragrance. It's how you're applying it.</p>" },
    content: { rendered: "<p>Fragrance longevity is almost entirely about skin preparation and application technique.</p><h2>Moisturise first</h2><p>Dry skin absorbs fragrance quickly and holds it poorly. Apply an unscented lotion to your pulse points before you spray—it gives the fragrance something to cling to.</p><h2>Don't rub</h2><p>Rubbing your wrists together breaks the top notes and makes the scent fade faster. Spray and leave it.</p><h2>Layer with body products</h2><p>If we carry a matching body lotion or oil for your scent, use it. The layered effect holds far longer than fragrance alone.</p><h2>Pulse points matter</h2><p>Wrists, neck, behind the ears, inner elbows. Anywhere your blood runs close to the surface—the warmth diffuses the scent naturally throughout the day.</p>" },
    date: "2025-04-01T09:00:00",
  },
];
